name: Daily Build
  on:
    schedule:
    - cron: '0 8 * * *' # 0 minute, 8th hour, every day of the month, every month, every day of the week (UTC)
  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
      - name: Trigger Netlify Build Hook
        run: curl -s -X POST -d {} "https://api.netlify.com/build_hooks/${TOKEN}"
        env:
          TOKEN: ${{ secrets.NETLIFY_DAILY_CRON_HOOK }}